configure: update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12933,6 +12933,19 @@ fi
 #       so lvresize can check detected flag here
 #
 DEFAULT_USE_BLKID_WIPING=0
+if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"blkid >= 2.24\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "blkid >= 2.24") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  HAVE_BLKID="yes"
+else
+  HAVE_BLKID="no"
+fi
+
+if test "$HAVE_BLKID" = "yes"
+then :
 
 
 pkg_failed=no
@@ -13024,10 +13037,9 @@ else
         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
 printf "%s\n" "yes" >&6; }
 
-	HAVE_BLKID=1
 
-	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for blkdid.h defines BLKID_SUBLKS_FSINFO." >&5
-printf %s "checking for blkdid.h defines BLKID_SUBLKS_FSINFO.... " >&6; }
+	{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for blkid.h defines BLKID_SUBLKS_FSINFO." >&5
+printf %s "checking for blkid.h defines BLKID_SUBLKS_FSINFO.... " >&6; }
 if test ${ac_cv_have_blkid_sublks_fsinfo+y}
 then :
   printf %s "(cached) " >&6
@@ -13057,7 +13069,7 @@ fi
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: $ac_cv_have_blkid_sublks_fsinfo" >&5
 printf "%s\n" "$ac_cv_have_blkid_sublks_fsinfo" >&6; }
 
-		if test $ac_cv_have_blkid_sublks_fsinfo = yes
+	if test $ac_cv_have_blkid_sublks_fsinfo = yes
 then :
 
 printf "%s\n" "#define HAVE_BLKID_SUBLKS_FSINFO 1" >>confdefs.h
@@ -13066,13 +13078,15 @@ fi
 
 fi
 
+fi
+
 if test "$BLKID_WIPING" != "no"
 then :
 
-	if test "$HAVE_BLKID" = 1
+	if test "$HAVE_BLKID" = "yes"
 then :
 
-		BLKID_WIPING=yes
+		BLKID_WIPING="yes"
 		BLKID_PC="blkid"
 		DEFAULT_USE_BLKID_WIPING=1
 
