Fix shared format1 build.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -309,7 +309,7 @@ ac_includes_default="\
 #endif"
 
 ac_default_prefix=/usr
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MSGFMT JOBS STATIC_LINK LVM1 OWNER GROUP CLDFLAGS CLDWHOLEARCHIVE CLDNOWHOLEARCHIVE LD_DEPS SOFLAG LVM_VERSION DEBUG DEVMAPPER HAVE_LIBDL CMDLIB LOCALEDIR INTL_PACKAGE INTL LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS AWK CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA LN_S SET_MAKE RANLIB ac_ct_RANLIB CPP EGREP build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os MSGFMT JOBS STATIC_LINK LVM1 OWNER GROUP CLDFLAGS CLDWHOLEARCHIVE CLDNOWHOLEARCHIVE LD_DEPS LD_FLAGS SOFLAG LVM_VERSION DEBUG DEVMAPPER HAVE_LIBDL CMDLIB LOCALEDIR INTL_PACKAGE INTL LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -3885,6 +3885,7 @@ case "$host_os" in
 		CLDWHOLEARCHIVE="-Wl,-whole-archive"
 		CLDNOWHOLEARCHIVE="-Wl,-no-whole-archive"
 		LD_DEPS=".export.sym"
+		LD_FLAGS="-Wl,--export-dynamic"
 		SOFLAG="-shared"
 		DEVMAPPER=yes
 		ODIRECT=yes ;;
@@ -3894,6 +3895,7 @@ case "$host_os" in
 		CLDWHOLEARCHIVE="-all_load"
 		CLDNOWHOLEARCHIVE=
 		LD_DEPS=
+		LD_FLAGS=
 		SOFLAG="-dynamiclib"
 		DEVMAPPER=no
 		ODIRECT=no ;;
@@ -4582,10 +4584,21 @@ else
 fi
 
 
-if test x$HAVE_LIBDL = xyes; then
+if [ "x$HAVE_LIBDL" = xyes -a "xSTATIC_LINK" = xno ]; then
 	CFLAGS="$CFLAGS -DHAVE_LIBDL"
 	LIBS="-ldl $LIBS"
+else
+	HAVE_LIBDL=no
 fi
+
+if [ "x$LVM1" = xshared -a "x$STATIC_LINK" = xyes ];
+ then  { { echo "$as_me:$LINENO: error: Features cannot be \"shared\" when building statically
+" >&5
+echo "$as_me: error: Features cannot be \"shared\" when building statically
+" >&2;}
+   { (exit 1); exit 1; }; }
+ exit
+fi;
 
 
 for ac_header in getopt.h
@@ -4968,6 +4981,7 @@ if test "-f VERSION"; then
 else
   LVM_VERSION="Unknown"
 fi
+
 
 
 
@@ -5678,6 +5692,7 @@ s,@CLDFLAGS@,$CLDFLAGS,;t t
 s,@CLDWHOLEARCHIVE@,$CLDWHOLEARCHIVE,;t t
 s,@CLDNOWHOLEARCHIVE@,$CLDNOWHOLEARCHIVE,;t t
 s,@LD_DEPS@,$LD_DEPS,;t t
+s,@LD_FLAGS@,$LD_FLAGS,;t t
 s,@SOFLAG@,$SOFLAG,;t t
 s,@LVM_VERSION@,$LVM_VERSION,;t t
 s,@DEBUG@,$DEBUG,;t t
