configure: Add LOCKDSANLOCK_SUPPORT for 5.0.0

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -12213,6 +12213,14 @@ fi
   test $ac_status = 0; }; then
   LOCKDSANLOCK_SUPPORT=420
 fi
+	if test -n "$PKG_CONFIG" && \
+    { { printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$PKG_CONFIG --exists --print-errors \"libsanlock_client >= 5.0.0\""; } >&5
+  ($PKG_CONFIG --exists --print-errors "libsanlock_client >= 5.0.0") 2>&5
+  ac_status=$?
+  printf "%s\n" "$as_me:${as_lineno-$LINENO}: \$? = $ac_status" >&5
+  test $ac_status = 0; }; then
+  LOCKDSANLOCK_SUPPORT=500
+fi
 
 pkg_failed=no
 { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for libsanlock_client >= 3.7.0" >&5
